definitions:
  handler.loginReq:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  handler.signupReq:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user and generate a JWT token.
      parameters:
      - description: User credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.loginReq'
      produces:
      - application/json
      responses:
        "200":
          description: token"="JWT token
          schema:
            additionalProperties: true
            type: object
        "400":
          description: error"="Bad request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: error"="Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Log in a user
      tags:
      - auth
  /api/v1/auth/signup:
    post:
      consumes:
      - application/json
      description: Create a new user account and generate a JWT token.
      parameters:
      - description: User credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.signupReq'
      produces:
      - application/json
      responses:
        "200":
          description: token"="JWT token
          schema:
            additionalProperties: true
            type: object
        "400":
          description: error"="Bad request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: error"="Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - auth
swagger: "2.0"
