name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        run: |
          eval "$(ssh-agent -s)"
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

      - name: Deploy to server
        env:
          SERVER: ${{ secrets.SERVER }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          # Test SSH connectivity to the server
          ssh -o StrictHostKeyChecking=no "$USERNAME@$SERVER" "echo 'SSH connection successful'"

          # Execute commands on the server
          ssh -o StrictHostKeyChecking=no "$USERNAME@$SERVER" << 'EOF'
            # Ensure that Go, Goose, and Swag are available by setting PATH explicitly
            export PATH=$PATH:/home/$USERNAME/go/bin:/usr/local/go/bin

            # Navigate to the project directory
            cd ~/naimix-hackathon/backend || exit

            # Pull the latest changes from the repository
            echo "Fetching latest code..."
            git fetch origin
            git reset --hard origin/main
            
            # Check if Go, Goose, and Swag are available
            echo "Checking Go installation..."
            go version || { echo "Go not installed!"; exit 1; }
            echo "Checking Goose installation..."
            goose -version || { echo "Goose not installed!"; exit 1; }
            echo "Checking Swag installation..."
            swag --version || { echo "Swag not installed!"; exit 1; }

            # Run migrations
            echo "Running migrations..."
            make migrate-up | sed 's|postgresql://[^"]*|postgresql://***REMOVED***|g'

            # Generate Swagger documentation
            echo "Generating Swagger documentation..."
            make swag

            # Build the project
            echo "Building the project..."
            make build

            # Stop the existing application if running
            echo "Stopping the existing application..."
            pkill -f './bin/main' || true

            # Start the new application
            echo "Starting the new application..."
            nohup ./bin/main > /dev/null 2>&1 &
          EOF
