name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER: ${{ secrets.SERVER }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          # Start SSH agent
          eval "$(ssh-agent -s)"

          # Load SSH private key
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

          # Execute commands on the server
          ssh -o StrictHostKeyChecking=no "$USERNAME@$SERVER" << 'EOF'
            export PATH=$PATH:/home/$USERNAME/go/bin:/usr/local/go/bin
            echo "Updated PATH: $PATH"
            
            # Navigate to the project directory
            cd ~/naimix-hackathon/backend || exit
            
            # Pull the latest changes from the repository
            git fetch origin
            git reset --hard origin/main
            
            # Run migrations (make sure to hide sensitive info in logs)
            echo "Running migrations..."
            make migrate-up | sed 's|postgresql://[^"]*|postgresql://***REMOVED***|g'

            # Generate Swagger documentation
            echo "Generating Swagger documentation..."
            make swag

            # Build the project
            echo "Building the project..."
            make build

            # Stop the existing application if running
            echo "Stopping the existing application..."
            pkill -f './bin/main' || true

            # Start the new application
            echo "Starting the new application..."
            nohup ./bin/main > /dev/null 2>&1 &
          EOF