name: Go CI
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22.1"

      - name: Backend dir
        run : cd ./backend

      - name: Install dependencies
        run: go mod tidy

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run go vet
        run: go vet ./...

      - name: Run golint
        run: golint ./...

      - name: Build the project
        run: go build -v ./...

      - name: Run tests
        run: go test ./...